# Generated by Django 4.2 on 2024-07-14 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NiceHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="введите название приятной привычки",
                        max_length=255,
                        verbose_name="Название приятной привычки",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="введите описание приятной привычки",
                        verbose_name="Описание приятной привычки",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приятная привычка",
                "verbose_name_plural": "Приятная привычки",
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="введите название привычки",
                        max_length=255,
                        verbose_name="Название привычки",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="введите описание привычки",
                        verbose_name="Описание привычки",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="введите место привычки",
                        max_length=255,
                        verbose_name="место",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Ежедневно"),
                            ("weekly", "Еженедельно"),
                            ("monthly", "Ежемесячно"),
                        ],
                        default="daily",
                        max_length=7,
                        verbose_name="Периодичность привычки",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Время начала привычки")),
                (
                    "action",
                    models.CharField(
                        help_text="введите действие привычки",
                        max_length=100,
                        verbose_name="Действие привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Награда за выполнение привычки",
                    ),
                ),
                (
                    "time_spent",
                    models.DurationField(
                        blank=True,
                        null=True,
                        verbose_name="Время затрачиваемое на привычку",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Публичная привычка"
                    ),
                ),
                (
                    "nice_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.nicehabit",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
