# Generated by Django 4.2 on 2024-07-14 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("daily", "Ежедневно"),
                    ("every_two_days", "Каждые два дня"),
                    ("every_three_days", "Каждые три дня"),
                    ("every_four_days", "Каждые четыре дня"),
                    ("every_five_days", "Каждые пять дней"),
                    ("every_six_days", "Каждые шесть дней"),
                    ("weekly", "Еженедельно"),
                ],
                default="daily",
                max_length=16,
                verbose_name="Периодичность привычки",
            ),
        ),
        migrations.CreateModel(
            name="EnjoyableHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="введите название приятной привычки",
                        max_length=255,
                        verbose_name="Название приятной привычки",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="введите описание приятной привычки",
                        verbose_name="Описание приятной привычки",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель привычки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Приятная привычка",
                "verbose_name_plural": "Приятная привычки",
            },
        ),
        migrations.AlterField(
            model_name="habit",
            name="nice_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="habits.enjoyablehabit",
                verbose_name="Приятная привычка",
            ),
        ),
        migrations.DeleteModel(
            name="NiceHabit",
        ),
    ]
