# Generated by Django 4.2 on 2024-07-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_alter_habit_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="nice_habit",
            field=models.CharField(max_length=10, verbose_name="Приятная привычка"),
        ),
        migrations.DeleteModel(
            name="EnjoyableHabit",
        ),
    ]
