# Generated by Django 4.2 on 2024-07-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0007_alter_habit_nice_habit_delete_enjoyablehabit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="nice_habit",
            new_name="is_nice_habit",
        ),
    ]
