# Generated by Django 4.2 on 2024-07-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0009_alter_habit_is_nice_habit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_nice_habit",
            field=models.BooleanField(default=False, verbose_name="Хорошая привычка"),
        ),
    ]
