# Generated by Django 4.2 on 2024-07-16 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0010_alter_habit_is_nice_habit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time_spent",
            field=models.DurationField(
                default=datetime.timedelta(seconds=120),
                verbose_name="Время затрачиваемое на привычку",
            ),
        ),
    ]
