# Generated by Django 4.2 on 2024-07-18 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0012_habit_associated_habit"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="start_date",
            field=models.DateField(
                default=datetime.date(2024, 7, 18), verbose_name="Дата выполнения"
            ),
        ),
    ]
