# Generated by Django 4.2 on 2024-08-01 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0013_habit_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="start_date",
            field=models.DateField(
                default=datetime.date(2024, 8, 1), verbose_name="Дата выполнения"
            ),
        ),
    ]
